import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local"
const inter = localfont({ src: './mc4.ttf' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
